version: '3'

services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advanced-calculator
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000 